@extends('admin.layout')

@section('title', 'Create Landing Page')

@section('content')
<h1 class="page-title">Create New Landing Page</h1>

<div class="card">
    <form method="POST" action="{{ route('admin.landing-systems.store') }}">
        @csrf
        
        <div class="form-group">
            <label for="name">Landing Page Name *</label>
            <input type="text" id="name" name="name" value="{{ old('name') }}" required placeholder="e.g., Systems Development Landing Page">
            @error('name')
                <small style="color: #e74c3c;">{{ $message }}</small>
            @enderror
        </div>
        
        <div class="form-group">
            <label for="slug">URL Slug *</label>
            <div style="display: flex; align-items: center; gap: 0.5rem;">
                <span style="color: #64748b;">/landing/</span>
                <input type="text" id="slug" name="slug" value="{{ old('slug') }}" required placeholder="systems" style="flex: 1;">
            </div>
            <small style="color: #64748b;">Used in URL: /landing/your-slug</small>
            @error('slug')
                <small style="color: #e74c3c; display: block;">{{ $message }}</small>
            @enderror
        </div>
        
        <div class="form-group">
            <label for="title">Page Title *</label>
            <input type="text" id="title" name="title" value="{{ old('title') }}" required placeholder="Custom System Development | Devvidia">
            <small style="color: #64748b;">Appears in browser tab</small>
            @error('title')
                <small style="color: #e74c3c; display: block;">{{ $message }}</small>
            @enderror
        </div>
        
        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" name="description" placeholder="Brief description of this landing page purpose">{{ old('description') }}</textarea>
            @error('description')
                <small style="color: #e74c3c;">{{ $message }}</small>
            @enderror
        </div>
        
        <div class="form-group">
            <label for="template">Template *</label>
            <select id="template" name="template" required>
                <option value="systems" {{ old('template') == 'systems' ? 'selected' : '' }}>Systems (Default)</option>
                <option value="custom" {{ old('template') == 'custom' ? 'selected' : '' }}>Custom</option>
            </select>
            <small style="color: #64748b;">Choose the design template for this landing page</small>
            @error('template')
                <small style="color: #e74c3c; display: block;">{{ $message }}</small>
            @enderror
        </div>
        
        <div class="form-group">
            <label style="display: flex; align-items: center; gap: 0.5rem; cursor: pointer;">
                <input type="checkbox" id="is_active" name="is_active" {{ old('is_active', true) ? 'checked' : '' }}>
                <span>Active (visitors can access this page)</span>
            </label>
        </div>
        
        <div style="display: flex; gap: 1rem;">
            <button type="submit" class="btn btn-success">Create Landing Page</button>
            <a href="{{ route('admin.landing-systems.index') }}" class="btn btn-primary">Cancel</a>
        </div>
    </form>
</div>

<script>
    // Auto-generate slug from name
    const nameInput = document.getElementById('name');
    const slugInput = document.getElementById('slug');
    
    nameInput.addEventListener('input', function() {
        if (!slugInput.value || slugInput.dataset.autoGenerated) {
            const slug = this.value
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-+|-+$/g, '');
            slugInput.value = slug;
            slugInput.dataset.autoGenerated = 'true';
        }
    });
    
    slugInput.addEventListener('input', function() {
        if (this.value) {
            this.dataset.autoGenerated = 'false';
        }
    });
</script>
@endsection
